### ISSUE TITLE
[Bug?] Fences and Furniture

### ISSUE THREAD

**Issue by ghost** [Zundrel/How-Bout-That-Furniture#4] opened 2017-09-12 08:40 UTC
There are several items, such as stools, chairs, fans, etc. that I don't think fences should connect to, as it can muddle the appearance of a build.

**Comment by Shrimpstress** [comment] 2017-09-12 13:49
It's a bug and I have found the cause. Build with a fix will be uploaded within the next 30 minutes or so.

**Comment by Shrimpstress** [comment] 2017-09-12 17:17
Bug has been fixed in 2.0.2 which came out a few hours ago.

**Comment by ghost** [comment] 2017-09-12 19:21
Please be aware that this bug has not been fixed in 2.0.2

**Comment by Shrimpstress** [comment] 2017-09-12 21:36
What type of stuff is it connecting to?

**Comment by ghost** [comment] 2017-09-12 21:44
Chairs, tables, fans, couches, etc. Pretty much everything.

**Comment by Shrimpstress** [comment] 2017-09-12 21:53
My bad, I thought you were referring to the fencing from my mod which had similar issues instead of vanilla fences. I found a fix for it already and will release a build within the next 30 minutes or so.

**Comment by Shrimpstress** [comment] 2017-09-12 22:17
2.0.3 is out now which should /actually/ fix the bug this time. Sorry about that xD.

**Closed as completed by Shrimpstress** 2017-09-12 22:17 UTC
Labels: bug
